// <auto-generated />
using System;
using System.Text.Json;
using FitnessApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessApp.Api.Migrations
{
    [DbContext(typeof(FitnessAppDbContext))]
    partial class FitnessAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<int>("EmailVerificationTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmailVerificationTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EmailVerificationTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EMAIL_VERIFICATION_TOKEN", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodId"));

                    b.Property<string>("Barcode")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("CaloriesPer100")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("CarbohydratesPer100")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FatPer100")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("ProteinPer100")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("FoodId");

                    b.HasIndex("Barcode");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name", "FoodId");

                    b.ToTable("FOOD", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.FoodLog", b =>
                {
                    b.Property<int>("FoodLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodLogId"));

                    b.Property<decimal>("CaloriesConsumed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("CarbohydratesConsumed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FatConsumed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProteinConsumed")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FoodLogId");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId", "ConsumedAt", "FoodLogId")
                        .IsDescending(false, true, true);

                    b.ToTable("FOOD_LOG", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.FoodServing", b =>
                {
                    b.Property<int>("FoodServingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodServingId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GramsPerUnit")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("FoodServingId");

                    b.HasIndex("FoodId", "Unit")
                        .IsUnique();

                    b.ToTable("FOOD_SERVING", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.LogEntry", b =>
                {
                    b.Property<long>("LogEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogEntryId"));

                    b.Property<string>("CorrelationId")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Exception")
                        .HasColumnType("varchar(8000)");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("MethodName")
                        .HasColumnType("varchar(200)");

                    b.Property<JsonDocument>("Parameters")
                        .HasColumnType("jsonb");

                    b.Property<string>("RequestPath")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LogEntryId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("UserId", "CreatedAt", "LogEntryId")
                        .IsDescending(false, true, true);

                    b.ToTable("LOG_ENTRY", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.MealCollection", b =>
                {
                    b.Property<int>("MealCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealCollectionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("MealCollectionId");

                    b.HasIndex("UserId", "CreatedAt", "MealCollectionId")
                        .IsDescending(false, true, true);

                    b.ToTable("MEAL_COLLECTION", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.MealItem", b =>
                {
                    b.Property<int>("MealItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealItemId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<int>("MealCollectionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("MealItemId");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealCollectionId");

                    b.ToTable("MEAL_ITEM", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("PASSWORD_RESET_TOKEN", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("REFRESH_TOKEN", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReminderId"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("ReminderTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("ReminderType")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ReminderId");

                    b.HasIndex("UserId");

                    b.ToTable("REMINDER", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.ReminderDelivery", b =>
                {
                    b.Property<long>("ReminderDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReminderDeliveryId"));

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReminderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReminderDeliveryId");

                    b.HasIndex("ReminderId", "ScheduledFor")
                        .IsUnique();

                    b.ToTable("REMINDER_DELIVERY", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320)");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<int>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserAchievementId"));

                    b.Property<int>("AchievementType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("UserId", "AchievementType")
                        .IsUnique();

                    b.ToTable("USER_ACHIEVEMENT", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserConsent", b =>
                {
                    b.Property<int>("UserConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserConsentId"));

                    b.Property<int>("ConsentType")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserConsentId");

                    b.HasIndex("UserId", "ConsentType", "GrantedAt");

                    b.ToTable("USER_CONSENT", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserDevice", b =>
                {
                    b.Property<int>("UserDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserDeviceId"));

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("ProtectedToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserDeviceId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("USER_DEVICE", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserGoal", b =>
                {
                    b.Property<int>("UserGoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserGoalId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetCarbohydrates")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("TargetDailyCalories")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("TargetFat")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("TargetProtein")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("TargetWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightChangePerWeek")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("UserGoalId");

                    b.HasIndex("UserId", "CreatedAt", "UserGoalId")
                        .IsDescending(false, true, true);

                    b.ToTable("USER_GOAL", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserProfileId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("DailySteps")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<decimal>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("StartingWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TrainingDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingIntensity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("WorkoutDurationMinutes")
                        .HasColumnType("integer");

                    b.HasKey("UserProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("USER_PROFILE", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserSetting", b =>
                {
                    b.Property<int>("UserSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserSettingId"));

                    b.Property<int>("SettingKey")
                        .HasColumnType("integer");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserSettingId");

                    b.HasIndex("UserId", "SettingKey")
                        .IsUnique();

                    b.ToTable("USER_SETTING", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.WeightLog", b =>
                {
                    b.Property<int>("WeightLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeightLogId"));

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("WeightLogId");

                    b.HasIndex("UserId", "RecordedDate")
                        .IsUnique();

                    b.HasIndex("UserId", "RecordedAt", "WeightLogId")
                        .IsDescending(false, true, true);

                    b.ToTable("WEIGHT_LOG", (string)null);
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.Food", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedFoods")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.FoodLog", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.Food", "Food")
                        .WithMany("FoodLogs")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.FoodServing", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.Food", "Food")
                        .WithMany("Servings")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.LogEntry", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("LogEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.MealCollection", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("MealCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.Food", "Food")
                        .WithMany("MealItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessApp.Api.Domain.Entities.MealCollection", "MealCollection")
                        .WithMany("Items")
                        .HasForeignKey("MealCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("MealCollection");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.ReminderDelivery", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.Reminder", "Reminder")
                        .WithMany("Deliveries")
                        .HasForeignKey("ReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reminder");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserConsent", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("UserConsents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserGoal", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("UserGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("FitnessApp.Api.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.UserSetting", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.WeightLog", b =>
                {
                    b.HasOne("FitnessApp.Api.Domain.Entities.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.Food", b =>
                {
                    b.Navigation("FoodLogs");

                    b.Navigation("MealItems");

                    b.Navigation("Servings");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.MealCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.Reminder", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("FitnessApp.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedFoods");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("FoodLogs");

                    b.Navigation("LogEntries");

                    b.Navigation("MealCollections");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reminders");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserConsents");

                    b.Navigation("UserDevices");

                    b.Navigation("UserGoals");

                    b.Navigation("UserProfile");

                    b.Navigation("UserSettings");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
